require('@rushstack/eslint-patch/modern-module-resolution');

/** @type {import('eslint').parserOptions} */
module.exports = {
  rules: {
    // basic
    'array-bracket-newline': 'off',
    'array-element-newline': 'off',
    'array-bracket-spacing': 'off',
    'block-spacing': 'off',
    'brace-style': 'off',
    'comma-spacing': 'off',
    'computed-property-spacing': 'off',
    'consistent-this': 'off',
    'eol-last': 'off',
    'function-call-argument-newline': 'off',
    'func-call-spacing': 'off',
    'function-paren-newline': 'off',
    'implicit-arrow-linebreak': 'off',
    indent: 'off',
    'key-spacing': 'off',
    'keyword-spacing': 'off',
    'line-comment-position': 'off',
    'linebreak-style': 'off',
    'lines-between-class-members': 'off',
    'lines-around-comment': 'off',
    'lines-around-directive': 'off',
    'newline-after-var': 'off',
    'newline-before-return': 'off',
    'newline-per-chained-call': 'off',
    'no-mixed-spaces-and-tabs': 'off',
    'no-multiple-empty-lines': 'off',
    'no-spaced-func': 'off',
    'no-tabs': 'off',
    'no-trailing-spaces': 'off',
    'no-whitespace-before-property': 'off',
    'object-curly-spacing': 'off',
    'object-curly-newline': 'off',
    'object-property-newline': 'off',
    'operator-linebreak': 'off',
    'padded-blocks': 'off',
    'padding-line-between-statements': 'off',
    'semi-spacing': 'off',
    'space-before-blocks': 'off',
    'space-before-function-paren': 'off',
    'space-in-parens': 'off',
    'space-infix-ops': 'off',
    'space-unary-ops': 'off',
    'spaced-comment': 'off',
    'switch-colon-spacing': 'off',
    'template-tag-spacing': 'off',
    'unicode-bom': 'off',
    // es6
    'arrow-spacing': 'off',
    'generator-star-spacing': 'off',
    'arrow-body-style': 'off',
    'rest-spread-spacing': 'off',
    'template-curly-spacing': 'off',
    'yield-star-spacing': 'off',
  },
};
